trigger:
- main

pool:
  vmImage: ubuntu-latest

# =========================
# 🔷 BUILD STAGE
# =========================
stages:

- stage: Build
  displayName: Build Java Application

  jobs:
  - job: MavenBuild
    displayName: Maven Build Job

    steps:

    # 🔹 Checkout code
    - checkout: self

    # 🔹 Build WAR using Maven
    - task: Maven@4
      displayName: Maven Clean Package
      inputs:
        mavenPomFile: 'pom.xml'
        goals: 'clean package'
        publishJUnitResults: true
        testResultsFiles: '**/surefire-reports/TEST-*.xml'
        javaHomeOption: 'JDKVersion'
        jdkVersionOption: '1.21'

    # 🔹 Verify WAR file
    - script: |
        echo "Checking build output..."
        ls -lh target
        jar -tf target/employee-app.war
      displayName: Verify WAR

    # 🔹 Publish artifact
    - publish: target/employee-app.war
      artifact: drop


# =========================
# 🔷 DEPLOY STAGE (EC2 + TOMCAT)
# =========================
- stage: Deploy_DEV
  displayName: Deploy to AWS EC2
  dependsOn: Build

  jobs:
  - job: Deploy
    displayName: Deploy WAR to EC2

    steps:

    # 🔹 Download artifact
    - download: current
      artifact: drop

    # =========================
    # 🔹 COPY WAR TO EC2
    # =========================
    - task: CopyFilesOverSSH@0
      displayName: Copy WAR to EC2
      inputs:
        sshEndpoint: 'EC2-DEV-SSH-CONN'   # 👈 MUST match Service Connection name
        sourceFolder: '$(Pipeline.Workspace)/drop'
        contents: 'employee-app.war'
        targetFolder: '/home/ubuntu/'      

    # =========================
    # 🔹 COPY Scripts TO EC2
    # =========================  
    - task: CopyFilesOverSSH@0
      displayName: Copy Deploy Script
      inputs:
        sshEndpoint: 'EC2-DEV-SSH-CONN'
        sourceFolder: '$(Build.SourcesDirectory)/scripts'
        contents: 'deploy.sh'
        targetFolder: '/home/ubuntu/'      
    
    # =========================
    # 🔹 DEPLOY TO TOMCAT
    # =========================
    - task: SSH@0
      displayName: Deploy WAR to Tomcat
      inputs:
        sshEndpoint: 'EC2-DEV-SSH-CONN'
        runOptions: 'commands'
        commands: |
          chmod +x /home/ubuntu/deploy.sh
          /home/ubuntu/deploy.sh

    # =========================
    # 🔹 HEALTH CHECK
    # =========================
    - task: SSH@0
      displayName: Health Check
      inputs:
        sshEndpoint: 'EC2-DEV-SSH-CONN'
        runOptions: 'commands'
        commands: |
          echo "Checking application health..."

          curl -f http://localhost:8080/employee-app/ || exit 1

          echo "Application is healthy ✔"